using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using UserServer.DAL.Models;

namespace UserServer.DAL.Configurations
{
    public class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder)
            {

            // confiugaraiton for user id that will be auto generated by postgrssql.
            builder.Property(e => e.Id).HasColumnName("User_id").HasDefaultValueSql("uuid_generate_v4()").IsRequired();

            builder.Property(u => u.Username)
                    .IsRequired()
                    .HasMaxLength(100);
         

            builder.Property(u => u.Email)
                    .IsRequired()
                    .HasMaxLength(100);

            builder.Property(u => u.Password)
                    .IsRequired()
                    .HasMaxLength(150);

            builder.HasIndex(u => u.Email).IsUnique();
            builder.HasIndex(u => u.Username).IsUnique();
            builder.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP").IsRequired();
            builder.HasData(new List<User>()
            {
                new User() {
                     Id = Guid.NewGuid(),
                    Username = "admin",
                    Email = "admin@gmail.com",
                    Role = "admin",
                    Password = "Admin123!"
                },
                new User() {
                     Id = Guid.NewGuid(),
                    Username = "user1",
                    Email = "user1@gmail.com",
                    Role = "user",
                    Password = "User1@123"
                },
                new User() {
                     Id = Guid.NewGuid(),
                    Username = "user2",
                    Email = "user2@gmail.com",
                    Role = "user",
                    Password = "User2@123"
                }


            });

        }
    }

}
